### ISSUE TITLE
上传zip文件的时候抛出异常

### ISSUE THREAD

**Issue by wugh** [mozillazg/baidu-pcs-python-sdk#1]
- 能够正常上传一个文本文件
- 在上传一个zip文件的时候报错，错误信息如下（看起来是编码问题），是不是后面post的时候编码导致
  https://gist.github.com/wugh/6885563

**Comment by mozillazg** [comment]
@wugh 好的，谢谢反馈！我会抽空尽快修复。

**Comment by wugh** [comment]
之前报错应该是因为这个文件是在windows下压缩，然后拿过来用的，所以报错。我在linux下用rar压缩，就不报错了

**Comment by mozillazg** [comment]
@wugh  你试一下将 `f = open(filename)` 改为 `f = open(fileaname, 'rb')` 试试，应该可以解决这个跨平台的编码问题。
对于二进制文件应该使用 `rb` 模式打开，不然会导致文件上传不完整。
