### ISSUE TITLE
好像已经不能用了

### ISSUE THREAD

**Issue by derekhe** [mozillazg/baidu-pcs-python-sdk#11]
无论什么token都返回400，似乎pcs API已经不能用了。

**Comment by mozillazg** [comment]
@derekhe 我会抽空看一下的。
你可以先试一下 https://github.com/ly0/baidupcsapi 这个项目。

**Comment by mozillazg** [comment]
@derekhe 我刚才试了一下 `info`, `meta`, `download` 这三个 api , 都可以使用。
获取 token 可以参考 https://github.com/mozillazg/baidu-pcs-python-sdk/wiki

**Comment by derekhe** [comment]
好的，但我用过你的测试用例里面的token，测试是failed的。

**Comment by mozillazg** [comment]
@derekhe 测试用例里的 token 已经过期了。

**Comment by derekhe** [comment]
好的，明白了。我去试试别的token，谢谢。

**Comment by derekhe** [comment]
我的问题和这个一样：
https://github.com/mozillazg/baidu-pcs-python-sdk/issues/10

现在已经无法申请PCS API了，所以不玩了。
