### ISSUE TITLE
SSL verify=True 似乎也不会有问题

### ISSUE THREAD

**Issue by jameswnzrf** [mozillazg/baidu-pcs-python-sdk#3]
我尝试了把verify=False删掉，也可以正常使用，可以考虑去掉verify=False。如果有必要，也可以让用户自己使用kwargs直接传这个参数给requests。谢谢！

**Comment by mozillazg** [comment]
@jameswnzrf  你好，请问你测试的是哪个 api？我这边上传 api 100% 会有错误：
`SSLError: hostname 'c.pcs.baidu.com' doesn't match u'pcs.baidu.com'`
方便的话，能否麻烦你修改 verify=True 后在项目根目录下执行一下 py.test 看看会不会报错？
谢谢！

**Comment by jameswnzrf** [comment]
你好，我试了一下，改了verify=True之后，py.test通过：31 passed in 130.58 seconds 
我用的是：platform linux -- Python 3.3.2 -- pytest-2.4.2 -- /usr/bin/python

**Comment by mozillazg** [comment]
@jameswnzrf 可能是我系统中的证书问题。
那就去掉 verify 参数，将 SSLError 加入到 FAQ 中。

**Comment by mozillazg** [comment]
Closed via 85b9105.
