### ISSUE TITLE
大文件不分片上传

### ISSUE THREAD

**Issue by jameswnzrf** [mozillazg/baidu-pcs-python-sdk#4]
你好，我试了一下用upload直接上传单个大文件(1G)，发现程序占用大量内存，可能是上传的时候把整个文件载入内存了？有没有可能让它不要把整个文件一次性载入内存？
虽然我知道可以分片上传，但是我想上传整个文件，因为我想能通过文件md5检验网盘上的内容是不是正确的，而分片合并了的文件md5就变了。所以我希望能整个上传单个大文件。
谢谢！

**Comment by mozillazg** [comment]
@jameswnzrf 嗯，我看看

**Comment by ly0** [comment]
requests不支持streaming，requests_toolbelt.MultipartEncoder 有现成的代码。
https://github.com/sigmavirus24/requests-toolbelt

``` python
body = MultipartEncoder(file)
headers = {
    "Content-Type": body.content_type
}
response = self.session.post(api, data=body, verify=False,headers=headers,**kwargs)
```

**Comment by mozillazg** [comment]
@ly0 嗯，我是看了你的项目才知道的这个用法。
我记得你当时说 PCS 不再支持百度网盘了，我当时看了一下，情况是这样的：
- 我在开发者控制台里找不到看 token 的地方了（之前建的测试项目的 token 过期了，并且测试项目也被百度删除了），所以没法测试。
- 百度关于 PCS 的文档已经被删除，所以这个项目可以结束了？

**Comment by ly0** [comment]
那个时候确实是关闭了，现在似乎又重新开放申请了。但是需要审核。
相关的链接
http://developer.baidu.com/console#manage/apilist!appid=APPID
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list
