### ISSUE TITLE
如何添加bt种子的离线下载任务？

### ISSUE THREAD

**Issue by noanti** [mozillazg/baidu-pcs-python-sdk#6]
不知道百度有没有给种子的离线下载的api？还有能不能把获取access token和刷新 token的功能也加入到这个sdk中，这样更方便些。或者有没有专门获取token的sdk？谢谢。

**Comment by mozillazg** [comment]
百度 PCS 本身没有提供种子以及 token 相关的 api.
关于添加种子任务你可以试一下这个项目：
[liyangjie/baidupcsapi](https://github.com/liyangjie/baidupcsapi) 
它有个添加 bt 任务的 api: http://baidupcsapi.readthedocs.org/en/latest/api.html#torrent .

**Comment by noanti** [comment]
十分感谢！
